[package]
name = "rasta"
version = "0.1.2"
edition = "2021"
respository = "https://github.com/zzjrabbit/rasta"
description = "UAST implemention"
license = "MIT/Apache-2.0"
keywords = ["uast"]

[dependencies]
serde = "1.0.207"
serde_derive = "1.0.207"
rmp-serde = "1.3.0"
